### ISSUE TITLE
Repository migration

### ISSUE THREAD

**Issue by mwestphal** [flathub/com.kitware.F3D#25]
F3D is now at : https://github.com/f3d-app/f3d

**Comment by kevinsmia1939** [comment]
Thanks for the heads-up.

**Comment by mwestphal** [comment]
I'm a bit confused, I do not see any related changes in the flathub repo.

**Comment by mwestphal** [comment]
Ok, looks like the package was updated to 1.1.1, but the website is still using the wrong url

**Comment by kevinsmia1939** [comment]
it is fixed now
