### ISSUE TITLE
No gui on Fedora 35

### ISSUE THREAD

**Issue by anderso** [flathub/com.kitware.F3D#43]
```
$ flatpak run com.kitware.F3D
$ echo $?
139
```
The run command immediately returns and no window is created. The exit code is 139. This happens on two separate Fedora 35 systems. The help text works though:

`$ flatpak run com.kitware.F3D --help`

The released binary (f3d-1.2.0-Linux.tar.gz) seems to work fine on the same systems.

**Comment by kevinsmia1939** [comment]
Hi,
What is the flatpak version you are using?
`flatpak --version`

**Comment by anderso** [comment]
```
$ flatpak --version
Flatpak 1.12.5
```

**Comment by kevinsmia1939** [comment]
Can you provide me with your hardware info?
`sudo lshw -short`

**Comment by anderso** [comment]
I just got an idea and tested it in xorg and it worked so my guess is you can reproduce it if you try in a wayland session. So my result is:
- Fedora 35/Gnome/Wayland -> Fail
- Fedora 35/Gnome/xorg -> Success

**Comment by kevinsmia1939** [comment]
> I just got an idea and tested it in xorg and it worked so my guess is you can reproduce it if you try in a wayland session. So my result is:
> 
>     * Fedora 35/Gnome/Wayland -> Fail
> 
>     * Fedora 35/Gnome/xorg -> Success

VTK that F3D use does not have Wayland support yet as far as I know, which might be why it does not work.

**Comment by anderso** [comment]
No, the same version of F3D in Wayland works for me on the same system, just not the flatpak version. So there seems to be an issue with the combination of Flatpak and Wayland.

**Comment by anderso** [comment]
I just discovered there are two instances of F3D on flathub. I tried the other one:

https://flathub.org/apps/details/io.github.f3d_app.f3d

and that one works and is newer so that solves my problem. It would be nice if this one could be removed or marked as deprecated or something, but you can close this issue if you like.

**Comment by kevinsmia1939** [comment]
> I just discovered there are two instances of F3D on flathub. I tried the other one:
> 
> https://flathub.org/apps/details/io.github.f3d_app.f3d
> 
> and that one works and is newer so that solves my problem. It would be nice if this one could be removed or marked as deprecated or something, but you can close this issue if you like.

Yes, it just recently been merge, I will mark it.
